version: "3.9"

networks:
  cfp-dev:
    driver: bridge

services:
  app:
    container_name: cfp
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "5000:5000"
    networks:
        - cfp-dev
    depends_on:
        - postgres_db
    environment:
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_URLS: http://*:5000

  postgres_db:
    container_name: postgres
    image: postgres:14.3-alpine
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345
        POSTGRES_DB: cfp
    ports:
        - "5432:5432" 
    networks:
        - cfp-dev
    volumes:
        - postgres-data:/var/lib/postgresql/data
    platform: linux/amd64

volumes:
    postgres-data: